name: 'coverage'
on:
  pull_request:
    branches:
      - master
      - main

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Install emacs
        run: sudo apt install emacs
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: ArtiomTr/jest-coverage-report-action@v2
        id: coverage
        with:
          annotations: none
          output: report-markdown
          test-script: npx jest -c jest-coverage.config.js
      - uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: ${{ steps.coverage.outputs.report }}
      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: coverage/lcov-report/index.html
