name: Docker Image CI

on:
  pull_request:
    branches: ["main"]
jobs:
  build_push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set Image Name
        run: echo "IMAGE_NAME=ghcr.io/vhdl-linter/vhdl-linter:${{github.event.pull_request && github.head_ref || github.ref_name}}" >> $GITHUB_ENV
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ env.IMAGE_NAME }}
          cache-from: type=registry,ref=ghcr.io/vhdl-linter/vhdl-linter:buildcache
          cache-to: type=registry,ref=ghcr.io/vhdl-linter/vhdl-linter:buildcache,mode=max