name: VUnit Compile

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  merge_group:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: VUnit/vunit_action@master
        with:
          cmd: python3 test/vunit_compile_test_no_error.py
